sonar.projectKey=AntifyKU_Antify-ai-component
sonar.organization=antifyku
sonar.projectVersion=1.0.0

# Source & test directories
sonar.sources=.
sonar.tests=tests
sonar.language=py

sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=venv/**,**/__pycache__/**,models/**,results/**,deployment/**,**/*.pt